  val productInputDeDupDF =  spark.read.table   .withColumnRenamed"prd_priceent_wrk.competitor_raw_product").where   .withColumnRename("shop_crawl_week_end_d='2023-11-11'")
  
  val resultdf =spark.read.orc   .withColumnRename("/common/SVPRIHDP/data/price/archival/DatasemblyResult/DIP/compacted_landing/date=2023-11-09")
val resultTransformedDf = spark.read.json   .withColumnRename(resultdf.selectExpr   .withColumnRename("value").as[String])

  val storedf =spark.read.orc   .withColumnRename("/common/SVPRIHDP/data/price/archival/DatasemblyStore/DIP/compacted_landing/date=2023-11-09")
val storeTransformedDf = spark.read.json   .withColumnRename(storedf.selectExpr   .withColumnRename("value").as[String])


 val datasembly_product_id : String = "datasembly_product_id"
  val datasembly_exp_product_id : String = "datasembly_exp_product_id"
  val export_id : String = "export_id"
  val surrogate_product_id : String = "surrogate_product_id"
  val banner_id : String = "banner_id"
  val chain : String = "chain"
  val banner : String = "banner"
  val host : String = "host"
  val sku : String = "sku"
  val upc_a : String = "upc_a"
  val brand : String = "brand"
  val description : String = "description"
  val size_text : String = "size_text"
  val size : String = "size"
  val size_units : String = "size_units"
  val category_level_0 : String = "category_level_0"
  val category_level_1 : String = "category_level_1"
  val category_level_2 : String = "category_level_2"
  val ds_brand : String = "ds_brand"
  val ds_description : String = "ds_description"
  val ds_size : String = "ds_size"
  val ds_size_units : String = "ds_size_units"
  val ds_category_level_0 : String = "ds_category_level_0"
  val ds_category_level_1 : String = "ds_category_level_1"
  val image_url : String = "image_url"
  val dpci : String = "dpci"
  val count : String = "count"
  val count_units : String = "count_units"
  val pack_count : String = "pack_count"
  val pack_count_units : String = "pack_count_units"
  val tcin : String = "tcin"
  val additional_description : String = "additional_description"
  val product_type : String = "product_type"
  val create_ts : String = "create_ts"
  val created_ts:String = "created_ts"
  val product_ingredients :String = "product_ingredients"
  val product_nutrition_info :String = "product_nutrition_info"
  val misc_data : String = "misc_data"


  //store raw columns
  val datasembly_store_id : String = "datasembly_store_id"
  val store_id : String = "store_id"
  val store_number : String = "store_number"
  val address : String = "address"
  val city : String = "city"
  val state : String = "state"
  val postal_code : String = "postal_code"
  val country : String = "country"
  val latitude : String = "latitude"
  val longitude : String = "longitude"
  val status : String = "status"
  val updated : String = "updated"

  //result raw columns
  val datasembly_result_id: String = "datasembly_result_id"
  val in_stock: String = "in_stock"
  val price_0_clearance: String = "price_0_clearance"
  val price_0_reduced: String = "price_0_reduced"
  val price_0_currency: String = "price_0_currency"
  val price_0_end: String = "price_0_end"
  val price_0_in_store_price: String = "price_0_in_store_price"
  val price_0_loyalty: String = "price_0_loyalty"
  val price_0_membership: String = "price_0_membership"
  val price_0_multiple: String = "price_0_multiple"
  val price_0_price: String = "price_0_price"
  val price_0_promotion: String = "price_0_promotion"
  val price_0_rollback: String = "price_0_rollback"
  val price_0_sold_per_unit: String = "price_0_sold_per_unit"
  val price_0_start: String = "price_0_start"
  val price_0_unit_price: String = "price_0_unit_price"
  val price_0_unit_price_multiple: String = "price_0_unit_price_multiple"
  val price_0_unit_price_units: String = "price_0_unit_price_units"
  val price_1_clearance: String = "price_1_clearance"
  val price_1_reduced: String = "price_1_reduced"
  val price_1_currency: String = "price_1_currency"
  val price_1_end: String = "price_1_end"
  val price_1_in_store_price: String = "price_1_in_store_price"
  val price_1_loyalty: String = "price_1_loyalty"
  val price_1_membership: String = "price_1_membership"
  val price_1_multiple: String = "price_1_multiple"
  val price_1_price: String = "price_1_price"
  val price_1_promotion: String = "price_1_promotion"
  val price_1_rollback: String = "price_1_rollback"
  val price_1_sold_per_unit: String = "price_1_sold_per_unit"
  val price_1_start: String = "price_1_start"
  val price_1_unit_price: String = "price_1_unit_price"
  val price_1_unit_price_multiple: String = "price_1_unit_price_multiple"
  val price_1_unit_price_units: String = "price_1_unit_price_units"
  val anomalous_price_flag : String = "anomalous_price_flag"
  val store_inferred: String = "store_inferred"
  val crawl_date : String = "crawl_date"
  val channel_method : String = "channel_method"

  val vendor_provided_store_id : String = "vendor_provided_store_id"
  val vendor_provided_export_product_id : String = "vendor_provided_export_product_id"
  val banner_n : String = "banner_n"
  val chain_n : String = "chain_n"
  val channel_method_n : String = "channel_method_n"
  val country_n : String = "country_n"
  val shop_create_utc_ts : String = "shop_create_utc_ts"
  val vendor_provided_result_id : String = "vendor_provided_result_id"
  val host_n : String = "host_n"
  val in_stock_f : String = "in_stock_f"
  val price_0_clearance_f : String = "price_0_clearance_f"
  val price_0_reduced_f : String = "price_0_reduced_f"
  val price_0_currency_c : String = "price_0_currency_c"
  val price_0_end_d : String = "price_0_end_d"
  val price_0_in_store_price_f : String = "price_0_in_store_price_f"
  val price_0_loyalty_f : String = "price_0_loyalty_f"
  val price_0_membership_f : String = "price_0_membership_f"
  val price_0_multiple_q : String = "price_0_multiple_q"
  val price_0_price_a : String = "price_0_price_a"
  val price_0_promotion_f : String = "price_0_promotion_f"
  val price_0_rollback_f : String = "price_0_rollback_f"
  val price_0_sold_per_unit_f : String = "price_0_sold_per_unit_f"
  val price_0_start_d : String = "price_0_start_d"
  val price_0_unit_price_a : String = "price_0_unit_price_a"
  val price_0_unit_price_multiple_q : String = "price_0_unit_price_multiple_q"
  val price_0_unit_price_uom : String = "price_0_unit_price_uom"
  val price_1_clearance_f : String = "price_1_clearance_f"
  val price_1_reduced_f : String = "price_1_reduced_f"
  val price_1_currency_c : String = "price_1_currency_c"
  val price_1_end_d : String = "price_1_end_d"
  val price_1_in_store_price_f : String = "price_1_in_store_price_f"
  val price_1_loyalty_f : String = "price_1_loyalty_f"
  val price_1_membership_f : String = "price_1_membership_f"
  val price_1_multiple_q : String = "price_1_multiple_q"
  val price_1_price_a : String = "price_1_price_a"
  val price_1_promotion_f : String = "price_1_promotion_f"
  val price_1_rollback_f : String = "price_1_rollback_f"
  val price_1_sold_per_unit_f : String = "price_1_sold_per_unit_f"
  val price_1_start_d : String = "price_1_start_d"
  val price_1_unit_price_a : String = "price_1_unit_price_a"
  val price_1_unit_price_multiple_q : String = "price_1_unit_price_multiple_q"
  val price_1_unit_price_uom : String = "price_1_unit_price_uom"
  val regular_retail_a : String = "regular_retail_a"
  val offer_retail_a : String = "offer_retail_a"
  val anomalous_price_f : String = "anomalous_price_f"
  val store_inferred_f : String = "store_inferred_f"
  val additional_product_desc : String = "additional_product_desc"
  val brand_n : String = "brand_n"
  val count_q : String = "count_q"
  val count_units_n : String = "count_units_n"
  val vendor_provided_product_id : String = "vendor_provided_product_id"
  val product_desc : String = "product_desc"
  val vendor_provided_brand_n : String = "vendor_provided_brand_n"
  val vendor_provided_category_level_0 : String = "vendor_provided_category_level_0"
  val vendor_provided_category_level_1 : String = "vendor_provided_category_level_1"
  val vendor_provided_desc : String = "vendor_provided_desc"
  val vendor_provided_size_q : String = "vendor_provided_size_q"
  val vendor_provided_size_units_n : String = "vendor_provided_size_units_n"
  val pack_count_q : String = "pack_count_q"
  val pack_count_units_n : String = "pack_count_units_n"
  val product_type_t : String = "product_type_t"
  val size_q : String = "size_q"
  val size_t : String = "size_t"
  val size_uom : String = "size_uom"
  val upc : String = "upc"
  val address_t : String = "address_t"
  val city_n : String = "city_n"
  val postal_c : String = "postal_c"
  val state_c : String = "state_c"
  val status_f : String = "status_f"
  val updated_d : String = "updated_d"
  val shop_crawl_d : String = "shop_crawl_d"
  val shop_crawl_week_end_d : String = "shop_crawl_week_end_d"
  val derived_chain_n : String = "derived_chain_n"
  val product_ingredients_t : String = "product_ingredients_t"
  val product_nutrition_info_t : String = "product_nutrition_info_t"
  val misc_data_t :String = "misc_data_t"
  val price_0_type : String = "price_0_type"
  val price_1_type : String = "price_1_type"
  val REG : String = "reg"
  val PROMO : String = "promo"
  val ROLLBACK : String = "rollback"

  
  
  val joinedDF = resultTransformedDf.join   .withColumnRename(productInputDeDupDF "datasembly_exp_product_id"="vendor_provided_export_product_id" "left").join   .withColumnRename(broadcast   .withColumnRename(storeTransformedDf) "vendor_provided_store_id"="datasembly_store_id" "left").select   .withColumnRename(INTERMEDIATE_TBL_SELECT_LIST.map   .withColumnRename(col): _*)
 

 val resultTransformedDf1 =  resultTransformedDf.withColumnRename(banner,banner_n).withColumnRename(chain,chain_n).withColumnRename(channel_method,channel_method_n).withColumnRename(country,country_n).withColumnRename(crawl_date,shop_crawl_d).withColumnRename(create_ts,shop_create_utc_ts).withColumnRename(datasembly_result_id,vendor_provided_result_id).withColumnRename(datasembly_store_id,vendor_provided_store_id).withColumnRename(datasembly_exp_product_id,vendor_provided_export_product_id).withColumnRename(host,host_n).withColumnRename(in_stock,in_stock_f).withColumnRename(price_0_clearance,price_0_clearance_f).withColumnRename(price_0_reduced,price_0_reduced_f).withColumnRename(price_0_currency,price_0_currency_c).withColumnRename(price_0_end,price_0_end_d).withColumnRename(price_0_in_store_price,price_0_in_store_price_f).withColumnRename(price_0_loyalty,price_0_loyalty_f).withColumnRename(price_0_membership,price_0_membership_f).withColumnRename(price_0_multiple,price_0_multiple_q).withColumnRename(price_0_price,price_0_price_a).withColumnRename(price_0_promotion,price_0_promotion_f).withColumnRename(price_0_rollback,price_0_rollback_f).withColumnRename(price_0_sold_per_unit,price_0_sold_per_unit_f).withColumnRename(price_0_start,price_0_start_d).withColumnRename(price_0_unit_price,price_0_unit_price_a).withColumnRename(price_0_unit_price_multiple,price_0_unit_price_multiple_q).withColumnRename(price_0_unit_price_units,price_0_unit_price_uom).withColumnRename(price_1_clearance,price_1_clearance_f).withColumnRename(price_1_currency,price_1_currency_c).withColumnRename(price_1_reduced,price_1_reduced_f).withColumnRename(price_1_end,price_1_end_d).withColumnRename(price_1_in_store_price,price_1_in_store_price_f).withColumnRename(price_1_loyalty,price_1_loyalty_f).withColumnRename(price_1_membership,price_1_membership_f).withColumnRename(price_1_multiple,price_1_multiple_q).withColumnRename(price_1_price,price_1_price_a).withColumnRename(price_1_promotion,price_1_promotion_f).withColumnRename(price_1_rollback,price_1_rollback_f).withColumnRename(price_1_sold_per_unit,price_1_sold_per_unit_f).withColumnRename(price_1_start,price_1_start_d).withColumnRename(price_1_unit_price,price_1_unit_price_a).withColumnRename(price_1_unit_price_multiple,price_1_unit_price_multiple_q).withColumnRename(price_1_unit_price_units,price_1_unit_price_uom).withColumnRename(anomalous_price_flag,anomalous_price_f).withColumnRename(store_inferred,store_inferred_f)

 


